"""Pre-parser transforms: when conditional expressions."""

from __future__ import annotations

import re
from typing import List, Tuple, Optional


class WhenMixin:
    """Mixin for transforming when expressions to CASE WHEN."""

    def _transform_when_expressions(self, text: str) -> str:
        """
        Transform when expressions to SQL CASE WHEN syntax.
        
        Simple case:
        when status is "active" then 1 → CASE WHEN status = 'active' THEN 1 END
        
        Implied equality:
        when status "active" then 1 → CASE WHEN status = 'active' THEN 1 END
        
        Comparison:
        when age < 4 then "infant" → CASE WHEN age < 4 THEN 'infant' END
        
        Searched case:
        when age < 18 then "Minor" → CASE WHEN age < 18 THEN 'Minor' END
        
        Multiple branches:
        when status
          is "active" then 1
          is "pending" then 0
          otherwise -1
        → CASE WHEN status = 'active' THEN 1 WHEN status = 'pending' THEN 0 ELSE -1 END
        """
        result = text
        
        # Find all "when" keywords (case-insensitive, word boundary)
        when_pattern = r'\bwhen\b'
        matches = list(re.finditer(when_pattern, result, re.IGNORECASE))
        
        # Process from end to start to avoid position shifts
        for match in reversed(matches):
            start_pos = match.start()
            
            # Skip if already inside a string or comment
            before = result[:start_pos]
            # Simple check: if odd number of quotes before, we're inside a string
            if (before.count("'") % 2 != 0) or (before.count('"') % 2 != 0):
                continue

            # Skip SQL "CASE WHEN" (and variants like "CASE\nWHEN") so we don't
            # reprocess CASE expressions generated by other transforms (e.g. pivot)
            # or written directly in embedded SQL.
            j = start_pos - 1
            while j >= 0 and result[j].isspace():
                j -= 1
            k = j
            while k >= 0 and (result[k].isalnum() or result[k] == "_"):
                k -= 1
            prev_word = result[k + 1 : j + 1].lower()
            if prev_word == "case":
                continue
            
            # Skip if we're inside an existing SQL CASE block (between CASE and END)
            if self._is_inside_case_block(result, start_pos):
                continue
            
            # Parse the when expression starting from this position
            case_expr, end_pos = self._parse_when_block(result, start_pos)
            
            if case_expr:
                # Replace the when expression with CASE expression
                result = result[:start_pos] + case_expr + result[end_pos:]
        
        return result

    def _is_inside_case_block(self, text: str, pos: int) -> bool:
        """
        Check if position is inside an existing SQL CASE ... END block.
        
        We look for unmatched 'case' keywords before this position.
        """
        # Count case and end keywords, respecting nesting
        # We need to find if there's an unmatched 'case' before this 'when'
        
        # Simple approach: scan backwards from pos looking for case/end keywords
        case_depth = 0
        i = pos - 1
        in_string = False
        string_char: Optional[str] = None
        
        while i >= 0:
            char = text[i]
            
            # Handle string boundaries (scanning backwards)
            if char in ("'", '"'):
                # Check if this is the end of a string or escaped
                if not in_string:
                    in_string = True
                    string_char = char
                elif char == string_char:
                    in_string = False
                    string_char = None
            
            if not in_string:
                # Check for 'end' keyword
                if i >= 2 and text[i-2:i+1].lower() == 'end':
                    # Check it's a word boundary
                    if (i - 3 < 0 or not text[i-3].isalnum() and text[i-3] != '_'):
                        if i + 1 >= len(text) or (not text[i+1].isalnum() and text[i+1] != '_'):
                            case_depth += 1  # Found an END, means we exited a CASE
                
                # Check for 'case' keyword
                if i >= 3 and text[i-3:i+1].lower() == 'case':
                    # Check it's a word boundary
                    if (i - 4 < 0 or not text[i-4].isalnum() and text[i-4] != '_'):
                        if i + 1 >= len(text) or (not text[i+1].isalnum() and text[i+1] != '_'):
                            case_depth -= 1  # Found a CASE, means we entered a CASE
                            if case_depth < 0:
                                # We're inside an unmatched CASE block
                                return True
            
            i -= 1
        
        return False
    
    def _parse_when_block(self, text: str, start_pos: int) -> Tuple[Optional[str], int]:
        """
        Parse a complete when block starting at start_pos.
        
        Returns:
            (case_expr, end_pos) or (None, start_pos) if parsing fails
        """
        pos = start_pos + 4  # Skip "when"

        # Skip whitespace (track whether "when" was on its own line).
        ws = []
        while pos < len(text) and text[pos] in " \t\n":
            ws.append(text[pos])
            pos += 1
        is_searched_case = "\n" in "".join(ws)
        
        if pos >= len(text):
            return None, start_pos
        
        branches: List[Tuple[str, str]] = []  # (condition, result) pairs
        else_value: Optional[str] = None
        base_expr: Optional[str] = None
        
        # Parse first branch
        first_condition, first_result, new_pos, is_simple = self._parse_when_branch(
            text, pos, None
        )
        if first_condition is None:
            return None, start_pos
        
        branches.append((first_condition, first_result))
        
        # Extract base_expr from first branch if it's a simple case (i.e. "when <expr> ...")
        if is_simple and not is_searched_case:
            base_expr = self._extract_base_expr(first_condition)
        
        pos = new_pos
        
        # Parse additional branches (they may be on new lines with indentation)
        while pos < len(text):
            # Skip whitespace and newlines, but remember where whitespace started so we
            # can preserve it if we decide there are no more branches (e.g. "... END as alias").
            ws_start = pos
            while pos < len(text) and text[pos] in " \t\n":
                pos += 1
            
            if pos >= len(text):
                break
            
            # Check for otherwise/else
            remaining = text[pos:].lower().lstrip()
            if remaining.startswith('otherwise') or remaining.startswith('else'):
                # Parse else value
                if remaining.startswith('otherwise'):
                    pos += text[pos:].lower().find('otherwise') + 9
                else:
                    pos += text[pos:].lower().find('else') + 4
                
                # Skip whitespace
                while pos < len(text) and text[pos] in ' \t\n':
                    pos += 1
                
                # Check if else value is a nested when expression
                # e.g., "else when x > 0 then 'yes' else 'no'"
                rest = text[pos:].lower().lstrip()
                if rest.startswith('when'):
                    # Recursively parse the nested when block
                    nested_case, pos = self._parse_when_block(text, pos)
                    if nested_case:
                        else_value = nested_case
                    else:
                        # Fallback to parsing as expression
                        else_value, pos = self._parse_expression(text, pos)
                else:
                    # Parse the else value as a regular expression
                    else_value, pos = self._parse_expression(text, pos)
                break
            
            # Check if there's another "when" branch (indented or on same line)
            # Look for patterns like: "is", "is not", "<", ">", "in", or a value
            # These indicate another branch
            
            # Try to parse another branch
            condition, result, new_pos, _ = self._parse_when_branch(
                text, pos, None if is_searched_case else base_expr
            )
            
            if condition is None:
                # No more branches
                pos = ws_start
                break
            
            branches.append((condition, result))
            pos = new_pos
        
        # Build CASE expression
        if not branches:
            return None, start_pos
        
        case_parts = ["CASE"]
        
        # Add WHEN clauses
        for condition, result in branches:
            case_parts.append(f"WHEN {condition} THEN {result}")
        
        if else_value:
            case_parts.append(f"ELSE {else_value}")
        
        case_parts.append("END")
        
        return " ".join(case_parts), pos
    
    def _parse_when_branch(
        self, text: str, start_pos: int, base_expr: Optional[str]
    ) -> Tuple[Optional[str], Optional[str], int, bool]:
        """
        Parse a single when branch.
        
        Returns:
            (condition, result, end_pos, is_simple_case)
        """
        pos = start_pos

        # Skip whitespace
        while pos < len(text) and text[pos] in " \t\n":
            pos += 1

        if pos >= len(text):
            return None, None, start_pos, False

        cond_start = pos

        condition: Optional[str] = None
        is_simple = False

        def _skip_ws(p: int) -> int:
            while p < len(text) and text[p] in " \t\n":
                p += 1
            return p

        # If base_expr is provided, branches may omit the expression and start with
        # operators/values (e.g. "is 'active' then ...", "< 4 then ...", "'active' then ...").
        if base_expr is not None:
            remaining = text[pos:].lower().lstrip()

            if remaining.startswith("is not"):
                pos = _skip_ws(pos + text[pos:].lower().find("is not") + 6)
                value, pos = self._parse_expression(text, pos)
                if value:
                    condition = f"{base_expr} != {value}"
                    is_simple = True
            elif remaining.startswith("is"):
                pos = _skip_ws(pos + text[pos:].lower().find("is") + 2)
                value, pos = self._parse_expression(text, pos)
                if value:
                    condition = f"{base_expr} = {value}"
                    is_simple = True
            elif remaining.startswith("in"):
                pos = _skip_ws(pos + text[pos:].lower().find("in") + 2)
                if pos < len(text) and text[pos] == "(":
                    values, pos = self._parse_value_list(text, pos)
                    condition = f"{base_expr} IN {values}"
                    is_simple = True
            else:
                # Comparators or implied equality value
                op = None
                if remaining.startswith("<="):
                    op = "<="
                    pos = _skip_ws(pos + 2)
                elif remaining.startswith(">="):
                    op = ">="
                    pos = _skip_ws(pos + 2)
                elif remaining.startswith("!=") or remaining.startswith("<>"):
                    op = "!="
                    pos = _skip_ws(pos + 2)
                elif remaining.startswith("<"):
                    op = "<"
                    pos = _skip_ws(pos + 1)
                elif remaining.startswith(">"):
                    op = ">"
                    pos = _skip_ws(pos + 1)
                elif remaining.startswith("="):
                    op = "="
                    pos = _skip_ws(pos + 1)

                if op is not None:
                    value, pos = self._parse_expression(text, pos)
                    if value:
                        condition = f"{base_expr} {op} {value}"
                        is_simple = True
                else:
                    value, pos = self._parse_expression(text, pos)
                    if value:
                        condition = f"{base_expr} = {value}"
                        is_simple = True

            if condition is None:
                return None, None, start_pos, False

        else:
            # Parse the expression/condition part for the first branch.
            expr, pos = self._parse_expression(text, pos)
            if expr is None:
                return None, None, start_pos, False

            pos = _skip_ws(pos)
            if pos >= len(text):
                return None, None, start_pos, False

            remaining = text[pos:].lower().lstrip()

            # Operator forms
            if remaining.startswith("is not"):
                pos = _skip_ws(pos + text[pos:].lower().find("is not") + 6)
                value, pos = self._parse_expression(text, pos)
                if value:
                    condition = f"{expr} != {value}"
                    is_simple = True
            elif remaining.startswith("is"):
                pos = _skip_ws(pos + text[pos:].lower().find("is") + 2)
                value, pos = self._parse_expression(text, pos)
                if value:
                    condition = f"{expr} = {value}"
                    is_simple = True
            elif remaining.startswith("in"):
                pos = _skip_ws(pos + text[pos:].lower().find("in") + 2)
                if pos < len(text) and text[pos] == "(":
                    values, pos = self._parse_value_list(text, pos)
                    condition = f"{expr} IN {values}"
                    is_simple = True
            else:
                # Comparators or implied equality / searched condition
                op = None
                if remaining.startswith("<="):
                    op = "<="
                    pos = _skip_ws(pos + 2)
                elif remaining.startswith(">="):
                    op = ">="
                    pos = _skip_ws(pos + 2)
                elif remaining.startswith("!=") or remaining.startswith("<>"):
                    op = "!="
                    pos = _skip_ws(pos + 2)
                elif remaining.startswith("<"):
                    op = "<"
                    pos = _skip_ws(pos + 1)
                elif remaining.startswith(">"):
                    op = ">"
                    pos = _skip_ws(pos + 1)
                elif remaining.startswith("="):
                    op = "="
                    pos = _skip_ws(pos + 1)

                if op is not None:
                    value, pos = self._parse_expression(text, pos)
                    if value:
                        condition = f"{expr} {op} {value}"
                        is_simple = True
                else:
                    # No operator immediately after expr. Try implied equality: "<value> then ..."
                    saved_pos = _skip_ws(pos)
                    next_expr, next_end = self._parse_expression(text, saved_pos)
                    if next_expr:
                        check_pos = _skip_ws(next_end)
                        if text[check_pos:].lower().lstrip().startswith("then"):
                            condition = f"{expr} = {next_expr}"
                            is_simple = True
                            pos = next_end
                        else:
                            condition = expr
                            is_simple = False
                    else:
                        condition = expr
                        is_simple = False

            if condition is None:
                return None, None, start_pos, False
        
        if condition is None:
            return None, None, start_pos, False
        
        # Now parse "then result"
        while pos < len(text) and text[pos] in ' \t\n':
            pos += 1
        
        if pos >= len(text):
            return None, None, start_pos, False
        
        remaining = text[pos:].lower().lstrip()
        if not remaining.startswith('then'):
            # Fallback: searched-case / complex-condition branches can have arbitrary
            # expressions before THEN (e.g. "age < 18 and country = ... then ...").
            p = cond_start
            paren_depth = 0
            in_string = False
            string_char: Optional[str] = None

            def is_word_boundary(idx: int) -> bool:
                if idx <= 0 or idx >= len(text):
                    return True
                return not (text[idx].isalnum() or text[idx] == "_")

            then_pos: Optional[int] = None
            while p < len(text):
                ch = text[p]
                if in_string:
                    if ch == string_char:
                        # Handle doubled quote escaping
                        if p + 1 < len(text) and text[p + 1] == string_char:
                            p += 2
                            continue
                        in_string = False
                        string_char = None
                    p += 1
                    continue

                if ch in ("'", '"'):
                    in_string = True
                    string_char = ch
                    p += 1
                    continue

                if ch == "(":
                    paren_depth += 1
                    p += 1
                    continue
                if ch == ")":
                    paren_depth = max(paren_depth - 1, 0)
                    p += 1
                    continue

                if paren_depth == 0 and text[p : p + 4].lower() == "then":
                    if is_word_boundary(p - 1) and is_word_boundary(p + 4):
                        then_pos = p
                        break

                p += 1

            if then_pos is None:
                return None, None, start_pos, False

            condition_raw = text[cond_start:then_pos].strip()
            # Normalize common ASQL sugar in conditions
            condition_raw = re.sub(r"\bis\s+not\b", "!=", condition_raw, flags=re.IGNORECASE)
            condition_raw = re.sub(r"\bis\b", "=", condition_raw, flags=re.IGNORECASE)

            pos = then_pos  # continue parsing from THEN
            condition = condition_raw
            is_simple = False
        
        pos += text[pos:].lower().find('then') + 4
        
        # Skip whitespace
        while pos < len(text) and text[pos] in ' \t\n':
            pos += 1
        
        # Parse result
        result, pos = self._parse_expression(text, pos)
        if result is None:
            return None, None, start_pos, False
        
        return condition, result, pos, is_simple
    
    def _extract_base_expr(self, condition: str) -> Optional[str]:
        """Extract base expression from a condition like 'status = value'."""
        # Simple extraction: take everything before the first operator
        for op in [' = ', ' != ', ' < ', ' > ', ' <= ', ' >= ', ' IN ']:
            if op in condition:
                return condition.split(op)[0].strip()
        return None
    
    def _parse_expression(self, text: str, start_pos: int) -> Tuple[Optional[str], int]:
        """
        Parse an expression (identifier, string, number, function call, etc.).
        
        Returns:
            (expression, end_pos)
        """
        pos = start_pos
        
        # Skip whitespace
        while pos < len(text) and text[pos] in ' \t\n':
            pos += 1
        
        if pos >= len(text):
            return None, start_pos
        
        # Check for string literal
        if text[pos] in '"\'':
            quote = text[pos]
            pos += 1
            start = pos
            while pos < len(text) and text[pos] != quote:
                if text[pos] == '\\':
                    pos += 1  # Skip escaped character
                pos += 1
            if pos < len(text):
                return text[start_pos:pos+1], pos + 1
            else:
                return None, start_pos
        
        # Check for number
        if text[pos].isdigit() or (text[pos] == '-' and pos + 1 < len(text) and text[pos + 1].isdigit()):
            start = pos
            if text[pos] == '-':
                pos += 1
            while pos < len(text) and (text[pos].isdigit() or text[pos] == '.'):
                pos += 1
            return text[start:pos], pos
        
        # Check for boolean/null
        remaining = text[pos:].lower()
        if remaining.startswith('true'):
            return text[pos:pos+4], pos + 4
        if remaining.startswith('false'):
            return text[pos:pos+5], pos + 5
        if remaining.startswith('null'):
            return text[pos:pos+4], pos + 4
        
        # Parse identifier or function call
        start = pos
        paren_depth = 0
        
        while pos < len(text):
            char = text[pos]
            
            if char == '(':
                paren_depth += 1
                pos += 1
            elif char == ')':
                if paren_depth > 0:
                    paren_depth -= 1
                    pos += 1
                else:
                    break
            elif char in ' \t\n,;':
                if paren_depth == 0:
                    break
                pos += 1
            elif char in '=<>!':
                # Operator - stop if not inside parens
                if paren_depth == 0:
                    break
                pos += 1
            else:
                pos += 1
        
        expr = text[start:pos].strip()
        if not expr:
            return None, start_pos
        
        return expr, pos
    
    def _parse_value_list(self, text: str, start_pos: int) -> Tuple[str, int]:
        """
        Parse a list of values: (value1, value2, ...)
        
        Returns:
            (value_list_string, end_pos)
        """
        pos = start_pos
        
        # Skip whitespace
        while pos < len(text) and text[pos] in ' \t\n':
            pos += 1
        
        if pos >= len(text) or text[pos] != '(':
            return '()', start_pos
        
        pos += 1  # Skip '('
        
        values = []
        paren_depth = 1
        
        while pos < len(text) and paren_depth > 0:
            # Skip whitespace
            while pos < len(text) and text[pos] in ' \t\n':
                pos += 1
            
            if pos >= len(text):
                break
            
            if text[pos] == ')':
                paren_depth -= 1
                if paren_depth == 0:
                    pos += 1
                    break
                pos += 1
            elif text[pos] == '(':
                paren_depth += 1
                pos += 1
            elif text[pos] == ',':
                pos += 1
            else:
                # Parse a value
                value, new_pos = self._parse_expression(text, pos)
                if value:
                    values.append(value)
                    pos = new_pos
                else:
                    pos += 1
        
        return '(' + ', '.join(values) + ')', pos
